In [6]:
import numpy as np

In [3]:
#random

np.random.seed(50)

x = np.random.random(5)
print(x)

y = np.random.randint(1,7,5)
print(y)

z = np.random.normal(0,1,5)
print(z)

q = np.arange(1,10)
choice = np.random.choice(q,3)
print(choice)

[0.49460165 0.2280831  0.25547392 0.39632991 0.3773151 ]
[6 6 3 3 5]
[-1.08153975 -0.1797424   0.31207884  0.06181543 -0.25827376]
[1 7 4]


In [4]:
a = np.arange(1,6)

mask = a > 2
print(a[mask])

result = np.where(a > 3, a, 0)
print(result)

[3 4 5]
[0 0 0 4 5]


In [15]:
o = np.arange(0,12)
r = o.reshape(2,2,3)
r=o.reshape(4,3)

print(o)
print(r)

f = r.flatten()
print(f)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#수학합수
m = np.array([4,25,9,16])
#제곱근, 지수, 로그
print(np.sqrt(m))
print(np.exp(m))
print(np.log(m))

#삼각함수
n = np.array([0,np.pi/2,np.pi])
print(n)
print(np.sin(n))
print(np.cos(n))

#행렬만들기
r = m.reshape(2,2)
print(r)

#전치행렬 만들어주기
t = r.transpose()
print(t)


[2. 5. 3. 4.]
[5.45981500e+01 7.20048993e+10 8.10308393e+03 8.88611052e+06]
[1.38629436 3.21887582 2.19722458 2.77258872]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[[ 4 25]
 [ 9 16]]
[[ 4  9]
 [25 16]]
